config/routes.rb
Dotfile::Application.routes.draw do
  resources :repos

  get "home/index"

  root :to => 'home#index'

end

app/models/repo.rb
class Repo < ActiveRecord::Base
  attr_accessible :url

  validates :url         , :presence => true
  validates :forks       , :presence => true
  validates :owner       , :presence => true
  validates :homepage    , :presence => true
  validates :watchers    , :presence => true
  #validates :description , :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @repos = Repo.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  # GET /repos
  # GET /repos.json
  def index
    @repos = Repo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @repos }
    end
  end

  # GET /repos/1
  # GET /repos/1.json
  def show
    @repo = Repo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @repo }
    end
  end

  # GET /repos/new
  # GET /repos/new.json
  def new
    @repo = Repo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @repo }
    end
  end

  # GET /repos/1/edit
  def edit
    @repo = Repo.find(params[:id])
  end

  # POST /repos
  # POST /repos.json
  def create
    @repo = Repo.new(params[:repo])

    respond_to do |format|
      if @repo.save
        format.html { redirect_to @repo, notice: 'Repo was successfully created.' }
        format.json { render json: @repo, status: :created, location: @repo }
      else
        format.html { render action: "new" }
        format.json { render json: @repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /repos/1
  # PUT /repos/1.json
  def update
    @repo = Repo.find(params[:id])

    respond_to do |format|
      if @repo.update_attributes(params[:repo])
        format.html { redirect_to @repo, notice: 'Repo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repos/1
  # DELETE /repos/1.json
  def destroy
    @repo = Repo.find(params[:id])
    @repo.destroy

    respond_to do |format|
      format.html { redirect_to repos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/home/index.html.erb
<h1><a href="/">dots...</a></h1>

<div class="panel">
  <h5>What is dotfiles?</h5>
  <p>dotfilesとは、ドットで始まるファイル(.emacs, .vimrc, .zshrc等...)をgitなどのバージョン管理ソフトで管理する際に、慣例的に用いられる<br />ディレクトリ名のことです。</p>
  <p> 参考) <%= link_to 'dotfiles.github.com', 'http://dotfiles.github.com' %></p>
  <p>dotsでは、githubで管理されているdotfilesたちを集めています。</p>
</div>

<table>
  <thead>
    <tr>
      <th>オーナー</th>
      <th>URL</th>
      <th>フォーク数</th>
      <th>ウォッチ数</th>
    </tr>
  </thead>
  <tbody>
    <% @repos.each do |repo| %>
    <tr>
      <td><%= link_to repo.owner, "https://github.com/#{repo.owner}" %></td>
      <td><%= link_to repo.url, repo.url %></td>
      <td><%= repo.forks %></td>
      <td><%= repo.watchers %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8" />
  <title>dots...</title>
  <meta name="keywords" content="dotfile,ドットファイル,dots,git,github" />
  <meta name="description" content="dotsはgithubにあるdotfilesを集めたサイトです" />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-12228362-13']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
</head>
<body>
  <%= csrf_meta_tags %>
  <div class "container">
    <div class="row">
      <div class="twelve columns">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/repos/_form.html.erb
<%= form_for(@repo) do |f| %>
  <% if @repo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repo.errors.count, "error") %> prohibited this repo from being saved:</h2>

      <ul>
      <% @repo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :forks %><br />
    <%= f.text_field :forks %>
  </div>
  <div class="field">
    <%= f.label :owner %><br />
    <%= f.text_field :owner %>
  </div>
  <div class="field">
    <%= f.label :homepage %><br />
    <%= f.text_field :homepage %>
  </div>
  <div class="field">
    <%= f.label :watchers %><br />
    <%= f.text_field :watchers %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :owner %><br />
    <%= f.text_field :owner %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repos/edit.html.erb
<h1>Editing repo</h1>

<%= render 'form' %>

<%= link_to 'Show', @repo %> |
<%= link_to 'Back', repos_path %>

app/views/repos/index.html.erb
<h1>Listing repos</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Url</th>
    <th>Forks</th>
    <th>Owner</th>
    <th>Homepage</th>
    <th>Watchers</th>
    <th>Description</th>
    <th>Owner</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @repos.each do |repo| %>
  <tr>
    <td><%= repo.name %></td>
    <td><%= repo.url %></td>
    <td><%= repo.forks %></td>
    <td><%= repo.owner %></td>
    <td><%= repo.homepage %></td>
    <td><%= repo.watchers %></td>
    <td><%= repo.description %></td>
    <td><%= repo.owner %></td>
    <td><%= link_to 'Show', repo %></td>
    <td><%= link_to 'Edit', edit_repo_path(repo) %></td>
    <td><%= link_to 'Destroy', repo, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Repo', new_repo_path %>

app/views/repos/new.html.erb
<h1>New repo</h1>

<%= render 'form' %>

<%= link_to 'Back', repos_path %>

app/views/repos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @repo.name %>
</p>

<p>
  <b>Url:</b>
  <%= @repo.url %>
</p>

<p>
  <b>Forks:</b>
  <%= @repo.forks %>
</p>

<p>
  <b>Owner:</b>
  <%= @repo.owner %>
</p>

<p>
  <b>Homepage:</b>
  <%= @repo.homepage %>
</p>

<p>
  <b>Watchers:</b>
  <%= @repo.watchers %>
</p>

<p>
  <b>Description:</b>
  <%= @repo.description %>
</p>

<p>
  <b>Owner:</b>
  <%= @repo.owner %>
</p>


<%= link_to 'Edit', edit_repo_path(@repo) %> |
<%= link_to 'Back', repos_path %>